pub mod armor;
pub mod body_zone;
pub mod constants;
pub mod morale;
pub mod penetration;
pub mod resolution;
pub mod skill;
pub mod stance;
pub mod trauma;
pub mod weapons;
pub mod wounds;

pub use body_zone::{BodyZone, WoundSeverity};
pub use weapons::{Edge, Mass, Reach, WeaponProperties, WeaponSpecial};
pub use armor::{Rigidity, Padding, Coverage, ArmorProperties};
pub use penetration::{PenetrationResult, resolve_penetration};
pub use trauma::{TraumaResult, resolve_trauma};
pub use wounds::{Wound, combine_results};
pub use stance::{CombatStance, TransitionTrigger, StanceTransitions};
pub use skill::{SkillLevel, CombatSkill};
pub use morale::{StressSource, MoraleState, BreakResult};
pub use resolution::{Combatant, ExchangeResult, resolve_exchange};
