pub mod perception;
pub mod thought_gen;
pub mod action_select;
pub mod action_execute;
pub mod tick;
pub mod resource_zone;
pub mod expectation_formation;
pub mod violation_detection;
pub mod rule_eval;
pub mod value_dynamics;
pub mod housing;
pub mod consumption;
pub mod population;

pub use resource_zone::{ResourceZone, ResourceType};
pub use expectation_formation::{record_observation, process_observations, infer_patterns_from_action};
pub use violation_detection::{check_violations, process_violations, ViolationType, check_pattern_violation};
pub use rule_eval::{evaluate_action_rules, select_idle_behavior};
pub use action_select::select_action_with_rules;
pub use value_dynamics::{apply_tick_dynamics, apply_event};
