pub mod value_access;
pub use value_access::ValueAccessor;

pub mod human;
pub mod orc;
pub mod kobold;
pub mod gnoll;
pub mod lizardfolk;
pub mod hobgoblin;
pub mod ogre;
pub mod harpy;
pub mod centaur;
pub mod minotaur;
pub mod satyr;
pub mod dryad;
pub mod goblin;
pub mod troll;
pub mod abyssal_demons;
pub mod elemental;
pub mod fey;
pub mod stone_giants;
pub mod golem;
pub mod merfolk;
pub mod naga;
pub mod revenant;
pub mod vampire;
pub mod lupine;
// CODEGEN: entity_species_mods
